services:
  postgresql:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init-sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  vault:
    image: hashicorp/vault:latest
    container_name: vault_container
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "my-root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK

  vault-setup:
    image: hashicorp/vault:latest
    container_name: vault_setup_container
    depends_on:
      vault:
        condition: service_started
    volumes:
      - ./vault-config:/vault-config
    entrypoint: /bin/sh -c "/vault-config/setup-vault.sh"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka:29093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'M_8g_9gRQp2_1Yh-gT7gHw'

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka_container
    ports:
      - "8761:8761"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user_service_container
    depends_on:
      postgresql:
        condition: service_started
      vault-setup:
        condition: service_completed_successfully
      redis:
        condition: service_started
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234567
      SPRING_CLOUD_VAULT_URI: http://vault:8200
      SPRING_CLOUD_VAULT_TOKEN: my-root-token
      SPRING_DATA_REDIS_HOST: redis
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

  booking-service:
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    container_name: booking_service_container
    depends_on:
      postgresql:
        condition: service_started
      vault-setup:
        condition: service_completed_successfully
      redis:
        condition: service_started
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/booking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234567
      SPRING_CLOUD_VAULT_URI: http://vault:8200
      SPRING_CLOUD_VAULT_TOKEN: my-root-token
      SPRING_DATA_REDIS_HOST: redis
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

  car-service:
    build:
      context: .
      dockerfile: car-service/Dockerfile
    container_name: car_service_container
    depends_on:
      postgresql:
        condition: service_started
      vault-setup:
        condition: service_completed_successfully
      redis:
        condition: service_started
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/car_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234567
      SPRING_CLOUD_VAULT_URI: http://vault:8200
      SPRING_CLOUD_VAULT_TOKEN: my-root-token
      SPRING_DATA_REDIS_HOST: redis
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

  car-details-service:
    build:
      context: .
      dockerfile: car-details-service/Dockerfile
    container_name: car_details_service_container
    depends_on:
      mongodb:
        condition: service_started
      kafka:
        condition: service_started
      eureka-server:
        condition: service_started
      vault-setup:
        condition: service_completed_successfully
      redis:
        condition: service_started
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/car_features
      SPRING_CLOUD_VAULT_URI: http://vault:8200
      SPRING_CLOUD_VAULT_TOKEN: my-root-token
      SPRING_DATA_REDIS_HOST: redis
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      user-service:
        condition: service_started
      booking-service:
        condition: service_started
      car-service:
        condition: service_started
      car-details-service:
        condition: service_started
      vault-setup:
        condition: service_completed_successfully
      eureka-server:
        condition: service_started
    environment:
      SERVER_PORT: 8080
      SPRING_CLOUD_VAULT_URI: http://vault:8200
      SPRING_CLOUD_VAULT_TOKEN: my-root-token
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    restart: unless-stopped

volumes:
  pgdata:
  mongodata: